export { default as Affix } from './affix'
export type { AffixProps } from './affix'
export { default as Alert } from './alert'
export { default as ConfigProvider } from './config-provider'
export { default as Space, SpaceCompact } from './space'
export type { SpaceProps, SpaceSize, SpaceSlots } from './space'
